/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface AuthSessions {
  expires_at: number;
  id: string;
  user_id: number;
}

export interface Options {
  created_at: Generated<string | null>;
  description: string | null;
  genre: string | null;
  gps_lat: number | null;
  gps_lng: number | null;
  id: Generated<number>;
  name: string;
  rating: number | null;
}

export interface Rounds {
  created_at: Generated<string | null>;
  ended_at: string | null;
  round: number;
  session_code: string;
  started_at: Generated<string | null>;
}

export interface SessionPlayers {
  joined_at: Generated<string | null>;
  session_code: string;
  user_id: number;
}

export interface Sessions {
  code: string;
  created_at: Generated<string | null>;
  gps_lat: number;
  gps_lng: number;
  owner_id: number;
}

export interface Users {
  created_at: Generated<string | null>;
  device_token: string;
  gps_lat: number | null;
  gps_lng: number | null;
  id: Generated<number>;
  username: string;
}

export interface Votes {
  id: Generated<number>;
  option_id: number;
  round_id: number;
  session_code: string;
  user_id: number;
  voted_at: Generated<string | null>;
}

export interface DB {
  auth_sessions: AuthSessions;
  options: Options;
  rounds: Rounds;
  session_players: SessionPlayers;
  sessions: Sessions;
  users: Users;
  votes: Votes;
}
